config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :brooms, except: [:update, :edit] do
    resources :reservations, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/broom.rb
class Broom < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :broom
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/brooms_controller.rb
class BroomsController < ApplicationController
  def index
    @brooms = Broom.all
  end

  def new
    @broom = Broom.new
  end

  def show
    @broom = Broom.find(params[:id])
  end

  def create
    @broom = Broom.new(broom_params)
    if @broom.save
      redirect_to @broom, notice: 'Broom was successfully created.'
    else
      render :new
    end
  end

  private

  def broom_params
    params.require(:broom).permit(:name, :description, :price, :twigs, :power, :age, :user_id, :image)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def new

    @broom = Broom.find(params[:broom_id])
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params)
    # we need `restaurant_id` to associate review with corresponding restaurant
    @broom = Broom.find(params[:broom_id])
    @reservation.broom = @broom
    @reservation.user = current_user
    if @reservation.save
      redirect_to broom_path(@broom), notice: "Your broom is flying home"
    else
      render :new
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to broom_path, notice: 'Reservation was successfully destroyed.'
  end

  private

  def reservation_params
    params.require(:reservation).permit(:date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/brooms/index.html.erb
<body class="background">
  <div class="box">
    <div id="map"></div>
    <div class="container1">
      <% @brooms.each do |broom| %>
      <div class="block">
        <div class="block_image">
          <%= cl_image_tag broom.photo.key %>
        </div>
        <div class="block_info" style="color:grey;">
          <div class="sep_block">
            <h3 style="color:black; font-family: Luminari, fantasy;"><%= broom.name %></h3>
            <div class="button_show">
              <td>
                <button type="button" class="btn btn-light btn_price"><%= link_to 'Info', broom_path(broom) %></td>
              </button>
            </div>
          </div>
          <br>
          <p>
            <i><%= broom.description %></p>
          </i>
          <br>
          <div class="sep_block">
            <p style="color:rgb(50, 50, 50); font-family: Luminari, fantasy;">
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/aurorerey", class: "avatar-bordered", alt: "avatar-bordered" %>
              <strong>
                Witch
                <%= broom.user.nickname %>
              </p>
            </strong>
            <p style="color:black; font-family: roboto;">
              <button type="button" class="btn btn-light btn_price">
                <%= broom.price %>
                $ /day
              </button>
            </p>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</body>

app/views/brooms/show.html.erb
<div class="container-show">
  <head></head>
  <body class="background">
  <div class="row">
    <div class="col-6">
      <div class= 'text-left'>
        <h1><%= @broom.name %></h1>
      </div>
      <div class="block">

        <div class="block_image">
        <%= cl_image_tag @broom.photo.key %>
        </div>
      </div>
    </div>


      <div class="text-left">
        <h3>-Balais entier</h3>
        <h3>-Norme covid à jour</h3>
        <h3>-Pas de remboursement</h3>
  <%= link_to "Book this broom!", new_broom_reservation_path(@broom), class: "nav-link" %>
      </div>
    </div>


<%= link_to 'Back', brooms_path %>

  <div class="row">
    <div class="col-6">
      <div class="block_info" style="color:white;">
        <div class='text-left'>
          <h3> Description </h3>
          <p><%= @broom.description %>
          <p><%= @broom.price %>$ /day</p>
          <p><%= @broom.twigs %> brindilles</p>
          <p><%= @broom.power %> cv</p>
          <p><%= @broom.age %> ans</p>
        </div>
      </div>
    </div>
  </div>
 </body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href='https://api.mapbox.com/mapbox-gl-js/v1.11.1/mapbox-gl.css' rel='stylesheet' />
    <title>WitchBroom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>

    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <% unless (controller_name == "reservations" && action_name == "new") ||
    (controller_name == "pages" && action_name == "home")  %>

     <%= render 'shared/footer' %>
    <% end %>


  </body>
</html>

app/views/pages/home.html.erb
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <title>Broom Witch</title>
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
  </head>

  <body>
    <div class="container">
      <h2>Find your dreamy Broom !</h2>
      <a href="/brooms" class="home_btn">LET'S RIDE</a>
    </div>
  </body>

</html>

app/views/reservations/new.html.erb
<h1 class="show">Nouvelle Réservation</h1>


<%= simple_form_for([@broom, @reservation]) do |f| %>
  <%= f.input :date, as: :date %>
  <%= f.submit %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <title>footer</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
  </head>


    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">


  <div id="footer">
  <ul class="list-inline">
    <li><a href="#"><i class="fab fa-youtube"></i></a></li>
    <li><a href="#"><i class="fab fa-facebook"></i></a></li>
    <li><a href="#"><i class="fab fa-twitter"></i></a></li>
    <li><a href="#"><i class="fab fa-github"></i></a></li>
  </ul>




    <p>This is a playground landing ©WitchBroom</p>
  </div>

app/views/shared/_navbar.html.erb
<div class="barnav">
  <h1>Broom Witch</h1>
<%# link_to 'Book', new_broom_reservaton_path(@broom) %>
  <div>
    <% if user_signed_in? %>
      <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>

    <% else %>
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
    <% end %>
  </div>


</div>